version: "3"
services:
  tg_bot_service:
    build: ./tg_bot_service
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - ./tg_bot_service:/app
    ports:
      - 8002:8002
    entrypoint: python3 ./main.py
